2025-02-19 18:18:15,345 - root - INFO - Start bot...
2025-02-19 18:18:15,345 - root - INFO - start pulling...
2025-02-19 18:18:32,247 - root - ERROR - Error: 1062 (23000): Duplicate entry '103416914' for key 'users.PRIMARY'
2025-02-19 18:19:46,319 - root - ERROR - Error: 1062 (23000): Duplicate entry '103416914' for key 'users.PRIMARY'
2025-02-19 18:27:32,913 - TeleBot - ERROR - Infinity polling: polling exited
2025-02-19 18:27:32,913 - TeleBot - ERROR - Break infinity polling
2025-02-19 18:27:32,914 - root - INFO - end pulling...
2025-02-19 18:29:25,017 - root - INFO - Start bot...
2025-02-19 18:29:25,018 - root - INFO - start pulling...
2025-02-19 18:29:29,230 - root - ERROR - Error: 1062 (23000): Duplicate entry '103416914' for key 'users.PRIMARY'
2025-02-19 18:31:48,296 - TeleBot - ERROR - Infinity polling: polling exited
2025-02-19 18:31:48,296 - TeleBot - ERROR - Break infinity polling
2025-02-19 18:31:48,297 - root - INFO - end pulling...
2025-02-19 18:31:50,742 - root - INFO - Start bot...
2025-02-19 18:31:50,742 - root - INFO - start pulling...
2025-02-19 18:32:17,316 - TeleBot - ERROR - Infinity polling: polling exited
2025-02-19 18:32:17,316 - TeleBot - ERROR - Break infinity polling
2025-02-19 18:32:17,316 - root - INFO - end pulling...
2025-02-19 18:32:19,439 - root - INFO - Start bot...
2025-02-19 18:32:19,440 - root - INFO - start pulling...
2025-02-19 18:32:44,135 - TeleBot - ERROR - Infinity polling: polling exited
2025-02-19 18:32:44,136 - TeleBot - ERROR - Break infinity polling
2025-02-19 18:32:44,137 - root - INFO - end pulling...
2025-02-19 18:32:46,718 - root - INFO - Start bot...
2025-02-19 18:32:46,718 - root - INFO - start pulling...
2025-02-19 18:37:18,362 - root - ERROR - Error: 1062 (23000): Duplicate entry '103416914' for key 'users.PRIMARY'
2025-02-19 22:24:50,784 - root - ERROR - Error: 1062 (23000): Duplicate entry '103416914' for key 'users.PRIMARY'
2025-02-20 00:50:55,530 - root - INFO - User 7469530070 added to database
2025-02-20 04:03:35,415 - root - INFO - User 7634084341 added to database
2025-02-20 04:51:48,202 - root - INFO - Start bot...
2025-02-20 04:51:48,202 - root - INFO - start pulling...
2025-02-20 04:51:54,658 - root - ERROR - Error: 1062 (23000): Duplicate entry '103416914' for key 'users.PRIMARY'
2025-02-20 04:53:44,280 - TeleBot - ERROR - Infinity polling: polling exited
2025-02-20 04:53:44,281 - TeleBot - ERROR - Break infinity polling
2025-02-20 04:53:44,281 - root - INFO - end pulling...
2025-02-20 04:53:48,140 - root - INFO - Start bot...
2025-02-20 04:53:48,140 - root - INFO - start pulling...
2025-02-20 04:53:50,924 - root - ERROR - Error: 1062 (23000): Duplicate entry '103416914' for key 'users.PRIMARY'
2025-02-20 04:55:23,970 - TeleBot - ERROR - Infinity polling: polling exited
2025-02-20 04:55:23,971 - TeleBot - ERROR - Break infinity polling
2025-02-20 04:55:23,971 - root - INFO - end pulling...
2025-02-20 04:55:27,435 - root - INFO - Start bot...
2025-02-20 04:55:27,436 - root - INFO - start pulling...
2025-02-20 04:55:35,909 - TeleBot - ERROR - Infinity polling exception: module 'Description' has no attribute 'funds_description'
2025-02-20 04:55:35,911 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\MochiServer_bot-2WiVER87\Lib\site-packages\telebot\__init__.py", line 1110, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                 logger_level=logger_level, allowed_updates=allowed_updates, restart_on_change=False,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                 *args, **kwargs)
                 ^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\.virtualenvs\MochiServer_bot-2WiVER87\Lib\site-packages\telebot\__init__.py", line 1198, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                            logger_level=logger_level, allowed_updates=allowed_updates)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\.virtualenvs\MochiServer_bot-2WiVER87\Lib\site-packages\telebot\__init__.py", line 1273, in __threaded_polling
    raise e
  File "C:\Users\Asus\.virtualenvs\MochiServer_bot-2WiVER87\Lib\site-packages\telebot\__init__.py", line 1235, in __threaded_polling
    self.worker_pool.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Asus\.virtualenvs\MochiServer_bot-2WiVER87\Lib\site-packages\telebot\util.py", line 150, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Asus\.virtualenvs\MochiServer_bot-2WiVER87\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\.virtualenvs\MochiServer_bot-2WiVER87\Lib\site-packages\telebot\__init__.py", line 9233, in _run_middlewares_and_handler
    result = handler['function'](message)
  File "c:\Users\Asus\Desktop\PythonProjects\MochiServer_bot\main.py", line 168, in callback
    bot.send_message(chat_id=call.message.chat.id, text=Des.funds_description, reply_markup=glass_markup)
                                                        ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'Description' has no attribute 'funds_description'. Did you mean: 'help_description'?

2025-02-20 04:56:05,628 - TeleBot - ERROR - Infinity polling: polling exited
2025-02-20 04:56:05,629 - TeleBot - ERROR - Break infinity polling
2025-02-20 04:56:05,629 - root - INFO - end pulling...
2025-02-20 04:56:14,179 - root - INFO - Start bot...
2025-02-20 04:56:14,179 - root - INFO - start pulling...
2025-02-20 04:56:20,376 - root - ERROR - Error: 1062 (23000): Duplicate entry '103416914' for key 'users.PRIMARY'
2025-02-20 05:10:22,309 - TeleBot - ERROR - Infinity polling: polling exited
2025-02-20 05:10:22,310 - TeleBot - ERROR - Break infinity polling
2025-02-20 05:10:22,310 - root - INFO - end pulling...
2025-02-20 05:10:25,391 - root - INFO - Start bot...
2025-02-20 05:10:25,391 - root - INFO - start pulling...
2025-02-20 05:10:32,384 - root - ERROR - Error: 1062 (23000): Duplicate entry '103416914' for key 'users.PRIMARY'
2025-02-20 05:10:37,206 - TeleBot - ERROR - Infinity polling exception: module 'Description' has no attribute 'discount_description'
2025-02-20 05:10:52,262 - TeleBot - ERROR - Infinity polling: polling exited
2025-02-20 05:10:52,263 - TeleBot - ERROR - Break infinity polling
2025-02-20 05:10:52,263 - root - INFO - end pulling...
2025-02-20 05:11:00,129 - root - INFO - Start bot...
2025-02-20 05:11:00,130 - root - INFO - start pulling...
2025-02-20 05:11:04,075 - root - ERROR - Error: 1062 (23000): Duplicate entry '103416914' for key 'users.PRIMARY'
2025-02-20 05:13:25,657 - TeleBot - ERROR - Infinity polling: polling exited
2025-02-20 05:13:25,659 - TeleBot - ERROR - Break infinity polling
2025-02-20 05:13:25,660 - root - INFO - end pulling...
2025-02-20 05:13:28,540 - root - INFO - Start bot...
2025-02-20 05:13:28,540 - root - INFO - start pulling...
2025-02-20 05:13:33,650 - root - ERROR - Error: 1062 (23000): Duplicate entry '103416914' for key 'users.PRIMARY'
2025-02-20 05:30:32,067 - TeleBot - ERROR - Infinity polling: polling exited
2025-02-20 05:30:32,068 - TeleBot - ERROR - Break infinity polling
2025-02-20 05:30:32,069 - root - INFO - end pulling...
2025-02-20 05:30:36,059 - root - INFO - Start bot...
2025-02-20 05:30:36,059 - root - INFO - start pulling...
2025-02-20 05:33:59,374 - root - ERROR - User already exist: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SET balance = balance + 40000 WHERE id = 103416914' at line 1
2025-02-20 05:38:53,430 - TeleBot - ERROR - Infinity polling: polling exited
2025-02-20 05:38:53,430 - TeleBot - ERROR - Break infinity polling
2025-02-20 05:38:53,430 - root - INFO - end pulling...
2025-02-20 05:38:56,417 - root - INFO - Start bot...
2025-02-20 05:38:56,418 - root - INFO - start pulling...
2025-02-20 05:39:03,492 - TeleBot - ERROR - Infinity polling: polling exited
2025-02-20 05:39:03,492 - TeleBot - ERROR - Break infinity polling
2025-02-20 05:39:03,492 - root - INFO - end pulling...
2025-02-20 05:41:06,926 - root - INFO - Start bot...
2025-02-20 05:41:06,927 - root - INFO - start pulling...
2025-02-20 05:41:07,990 - root - ERROR - User already exist: 1054 (42S22): Unknown column 'balance' in 'field list'
2025-02-20 05:41:43,274 - root - ERROR - User already exist: 1054 (42S22): Unknown column 'balance' in 'field list'
2025-02-20 05:42:24,638 - root - ERROR - User already exist: 1054 (42S22): Unknown column 'balance' in 'field list'
2025-02-20 05:46:02,304 - root - INFO - User 7634084341 added to database
2025-02-20 05:49:03,242 - TeleBot - ERROR - Infinity polling: polling exited
2025-02-20 05:49:03,242 - TeleBot - ERROR - Break infinity polling
2025-02-20 05:49:03,243 - root - INFO - end pulling...
2025-02-20 05:49:05,531 - root - INFO - Start bot...
2025-02-20 05:49:05,532 - root - INFO - start pulling...
2025-02-20 05:49:21,572 - root - INFO - User 7634084341 added to database
2025-02-20 06:04:09,539 - TeleBot - ERROR - Infinity polling: polling exited
2025-02-20 06:04:09,540 - TeleBot - ERROR - Break infinity polling
2025-02-20 06:04:09,540 - root - INFO - end pulling...
2025-02-20 06:13:30,084 - root - INFO - Start bot...
2025-02-20 06:13:30,084 - root - INFO - start pulling...
2025-02-20 06:13:36,680 - root - INFO - end pulling...
2025-02-20 06:35:31,361 - root - INFO - Start bot...
2025-02-20 06:35:31,361 - root - INFO - start pulling...
2025-02-20 06:35:36,753 - root - ERROR - User already exist: 1062 (23000): Duplicate entry '103416914' for key 'users.PRIMARY'
2025-02-20 06:36:31,183 - root - INFO - Start bot...
2025-02-20 06:36:31,184 - root - INFO - start pulling...
2025-02-20 06:36:36,072 - root - ERROR - User already exist: 1062 (23000): Duplicate entry '103416914' for key 'users.PRIMARY'
2025-02-20 06:38:55,342 - root - ERROR - User already exist: 1062 (23000): Duplicate entry '103416914' for key 'users.PRIMARY'
2025-02-20 06:39:26,063 - root - INFO - Start bot...
2025-02-20 06:39:26,063 - root - INFO - start pulling...
2025-02-20 06:39:29,584 - root - ERROR - User already exist: 1062 (23000): Duplicate entry '103416914' for key 'users.PRIMARY'
2025-02-20 06:39:52,807 - root - INFO - end pulling...
2025-02-20 06:40:04,736 - root - INFO - Start bot...
2025-02-20 06:40:04,736 - root - INFO - start pulling...
2025-02-20 06:54:35,767 - root - INFO - end pulling...
2025-02-20 06:54:39,374 - root - INFO - Start bot...
2025-02-20 06:54:39,375 - root - INFO - start pulling...
2025-02-20 07:04:29,771 - root - ERROR - User already exist: 1062 (23000): Duplicate entry '103416914' for key 'users.PRIMARY'
2025-02-20 07:07:14,376 - root - INFO - end pulling...
2025-02-20 07:09:58,990 - root - INFO - Start bot...
2025-02-20 07:09:58,990 - root - INFO - start pulling...
2025-02-20 07:23:02,196 - root - INFO - end pulling...
2025-02-20 07:23:19,025 - root - INFO - Start bot...
2025-02-20 07:23:19,025 - root - INFO - start pulling...
2025-02-20 07:23:25,575 - root - ERROR - User already exist: 1062 (23000): Duplicate entry '103416914' for key 'users.PRIMARY'
2025-02-20 07:26:24,841 - root - INFO - end pulling...
2025-02-20 07:26:35,544 - root - INFO - Start bot...
2025-02-20 07:26:35,544 - root - INFO - start pulling...
2025-02-20 07:26:40,811 - root - ERROR - User already exist: 1062 (23000): Duplicate entry '103416914' for key 'users.PRIMARY'
2025-02-20 07:38:56,743 - root - INFO - end pulling...
2025-02-20 07:39:01,981 - root - INFO - Start bot...
2025-02-20 07:39:01,981 - root - INFO - start pulling...
2025-02-20 07:57:34,828 - root - INFO - end pulling...
2025-02-20 07:57:37,447 - root - INFO - Start bot...
2025-02-20 07:57:37,447 - root - INFO - start pulling...
2025-02-20 08:00:35,283 - root - ERROR - User already exist: 1062 (23000): Duplicate entry '103416914' for key 'users.PRIMARY'
2025-02-20 08:01:05,563 - root - ERROR - User already exist: 1062 (23000): Duplicate entry '103416914' for key 'users.PRIMARY'
2025-02-20 08:05:19,438 - root - INFO - end pulling...
2025-02-20 08:05:32,089 - root - INFO - Start bot...
2025-02-20 08:05:32,089 - root - INFO - start pulling...
2025-02-20 08:05:37,663 - root - ERROR - User already exist: 1062 (23000): Duplicate entry '103416914' for key 'users.PRIMARY'
2025-02-20 08:15:04,710 - root - INFO - end pulling...
2025-02-20 08:15:10,428 - root - INFO - Start bot...
2025-02-20 08:15:10,428 - root - INFO - start pulling...
2025-02-20 08:17:18,106 - root - ERROR - User already exist: 1062 (23000): Duplicate entry '7469530070' for key 'users.PRIMARY'
2025-02-20 09:59:51,822 - root - ERROR - User already exist: 1062 (23000): Duplicate entry '7469530070' for key 'users.PRIMARY'
2025-02-20 15:46:45,787 - root - INFO - User 7634084341 added to database
2025-02-20 17:34:54,202 - root - INFO - end pulling...
2025-02-20 17:35:00,785 - root - INFO - Start bot...
2025-02-20 17:35:00,786 - root - INFO - start pulling...
2025-02-20 17:38:33,110 - root - INFO - end pulling...
2025-02-20 17:38:36,719 - root - INFO - Start bot...
2025-02-20 17:38:36,719 - root - INFO - start pulling...
2025-02-20 17:49:28,376 - root - INFO - end pulling...
2025-02-20 17:52:28,933 - root - INFO - Start bot...
2025-02-20 17:52:28,933 - root - INFO - start pulling...
2025-02-20 17:54:40,220 - root - INFO - Start bot...
2025-02-20 17:54:40,221 - root - INFO - start pulling...
2025-02-20 17:54:46,712 - root - INFO - end pulling...
2025-02-20 17:55:08,119 - root - INFO - Start bot...
2025-02-20 17:55:08,119 - root - INFO - start pulling...
2025-02-20 17:55:19,943 - root - ERROR - User already exist: 1062 (23000): Duplicate entry '103416914' for key 'users.PRIMARY'
2025-02-20 18:06:07,199 - root - INFO - Start bot...
2025-02-20 18:06:07,200 - root - INFO - start pulling...
2025-02-20 18:12:14,715 - root - INFO - Start bot...
2025-02-20 18:12:14,715 - root - INFO - start pulling...
2025-02-20 18:12:51,866 - root - INFO - Start bot...
2025-02-20 18:12:51,866 - root - INFO - start pulling...
2025-02-20 18:17:43,264 - root - INFO - Start bot...
2025-02-20 18:17:43,264 - root - INFO - start pulling...
2025-02-20 21:28:37,527 - root - INFO - Start bot...
2025-02-20 21:28:37,527 - root - INFO - start pulling...
2025-02-20 21:34:39,631 - root - INFO - Start bot...
2025-02-20 21:34:39,631 - root - INFO - start pulling...
2025-02-20 22:03:29,864 - root - INFO - end pulling...
2025-02-20 22:03:37,305 - root - INFO - Start bot...
2025-02-20 22:03:37,306 - root - INFO - start pulling...
2025-02-20 22:18:48,746 - root - INFO - end pulling...
2025-02-20 22:18:51,339 - root - INFO - Start bot...
2025-02-20 22:18:51,339 - root - INFO - start pulling...
2025-02-20 22:19:51,828 - root - ERROR - User already exist: 1062 (23000): Duplicate entry '103416914' for key 'users.PRIMARY'
2025-02-20 22:21:29,409 - root - INFO - Start bot...
2025-02-20 22:21:29,409 - root - INFO - start pulling...
2025-02-20 22:21:32,798 - root - ERROR - User already exist: 1062 (23000): Duplicate entry '103416914' for key 'users.PRIMARY'
2025-02-20 22:22:37,708 - root - ERROR - User already exist: 1062 (23000): Duplicate entry '7634084341' for key 'users.PRIMARY'
2025-02-20 23:05:46,798 - root - INFO - end pulling...
2025-02-20 23:05:51,992 - root - INFO - Start bot...
2025-02-20 23:05:51,992 - root - INFO - start pulling...
2025-02-20 23:09:36,623 - root - INFO - Start bot...
2025-02-20 23:09:36,623 - root - INFO - start pulling...
2025-02-20 23:09:39,124 - root - ERROR - User already exist: 1062 (23000): Duplicate entry '7469530070' for key 'users.PRIMARY'
2025-02-20 23:09:39,147 - root - ERROR - User already exist: 1062 (23000): Duplicate entry '7469530070' for key 'users.PRIMARY'
2025-02-20 23:09:43,376 - root - ERROR - User already exist: 1062 (23000): Duplicate entry '103416914' for key 'users.PRIMARY'
2025-02-20 23:14:24,405 - root - INFO - Start bot...
2025-02-20 23:14:24,405 - root - INFO - start pulling...
2025-02-20 23:23:46,680 - root - INFO - Start bot...
2025-02-20 23:23:46,680 - root - INFO - start pulling...
2025-02-20 23:23:49,829 - root - ERROR - User already exist: 1062 (23000): Duplicate entry '7469530070' for key 'users.PRIMARY'
2025-02-20 23:25:15,297 - root - INFO - end pulling...
2025-02-20 23:25:18,019 - root - INFO - Start bot...
2025-02-20 23:25:18,019 - root - INFO - start pulling...
2025-02-20 23:26:50,706 - root - INFO - end pulling...
2025-02-20 23:26:53,749 - root - INFO - Start bot...
2025-02-20 23:26:53,749 - root - INFO - start pulling...
2025-02-21 00:26:26,223 - root - INFO - end pulling...
2025-02-21 00:26:29,589 - root - INFO - Start bot...
2025-02-21 00:26:29,589 - root - INFO - start pulling...
2025-02-21 00:28:17,599 - root - INFO - end pulling...
2025-02-21 00:35:40,574 - root - INFO - Start bot...
2025-02-21 00:35:40,575 - root - INFO - start pulling...
2025-02-21 00:42:41,824 - root - INFO - Start bot...
2025-02-21 00:42:41,825 - root - INFO - start pulling...
2025-02-21 00:47:16,988 - root - INFO - Start bot...
2025-02-21 00:47:16,988 - root - INFO - start pulling...
2025-02-21 02:03:33,197 - root - INFO - Start bot...
2025-02-21 02:03:33,197 - root - INFO - start pulling...
2025-02-21 02:08:30,230 - root - INFO - Start bot...
2025-02-21 02:08:30,230 - root - INFO - start pulling...
2025-02-21 02:12:56,297 - root - INFO - Start bot...
2025-02-21 02:12:56,297 - root - INFO - start pulling...
2025-02-22 18:34:55,969 - root - INFO - Start bot...
2025-02-22 18:34:55,969 - root - INFO - start pulling...
2025-02-22 20:50:33,566 - root - INFO - User 161008342 added to database
2025-02-23 19:53:20,365 - root - INFO - Start bot...
2025-02-23 19:53:20,365 - root - INFO - start pulling...
2025-02-23 19:56:36,807 - root - INFO - Start bot...
2025-02-23 19:56:36,807 - root - INFO - start pulling...
2025-02-23 19:58:31,183 - root - INFO - Start bot...
2025-02-23 19:58:31,183 - root - INFO - start pulling...
2025-02-23 20:04:33,104 - root - INFO - Start bot...
2025-02-23 20:04:33,105 - root - INFO - start pulling...
2025-02-23 20:05:07,416 - root - INFO - Start bot...
2025-02-23 20:05:07,417 - root - INFO - start pulling...
2025-02-23 20:07:49,050 - root - INFO - Start bot...
2025-02-23 20:07:49,051 - root - INFO - start pulling...
2025-02-23 20:08:58,128 - root - INFO - Start bot...
2025-02-23 20:08:58,128 - root - INFO - start pulling...
2025-02-23 20:11:16,646 - root - INFO - Start bot...
2025-02-23 20:11:16,646 - root - INFO - start pulling...
2025-02-23 20:16:03,750 - root - INFO - Start bot...
2025-02-23 20:16:03,751 - root - INFO - start pulling...
2025-02-23 20:18:37,543 - root - INFO - Start bot...
2025-02-23 20:18:37,544 - root - INFO - start pulling...
2025-02-23 20:19:10,040 - root - INFO - Start bot...
2025-02-23 20:19:10,040 - root - INFO - start pulling...
2025-02-23 20:19:57,235 - root - INFO - Start bot...
2025-02-23 20:19:57,236 - root - INFO - start pulling...
2025-02-23 20:20:37,007 - root - INFO - Start bot...
2025-02-23 20:20:37,008 - root - INFO - start pulling...
2025-02-23 20:21:09,265 - root - INFO - Start bot...
2025-02-23 20:21:09,265 - root - INFO - start pulling...
2025-02-23 20:21:54,986 - root - INFO - Start bot...
2025-02-23 20:21:54,987 - root - INFO - start pulling...
2025-02-23 20:22:10,364 - root - INFO - Start bot...
2025-02-23 20:22:10,365 - root - INFO - start pulling...
2025-02-23 20:26:17,089 - root - INFO - Start bot...
2025-02-23 20:26:17,089 - root - INFO - start pulling...
2025-02-23 20:27:06,466 - root - INFO - Start bot...
2025-02-23 20:27:06,467 - root - INFO - start pulling...
2025-02-23 20:27:08,986 - root - ERROR - Error while deleting message: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: message to delete not found
2025-02-23 20:32:23,537 - root - INFO - Start bot...
2025-02-23 20:32:23,538 - root - INFO - start pulling...
2025-02-23 20:37:51,771 - root - INFO - Start bot...
2025-02-23 20:37:51,772 - root - INFO - start pulling...
2025-02-23 20:43:57,674 - root - INFO - Start bot...
2025-02-23 20:43:57,675 - root - INFO - start pulling...
2025-02-23 20:45:28,655 - root - INFO - Start bot...
2025-02-23 20:45:28,655 - root - INFO - start pulling...
2025-02-23 20:45:48,480 - root - INFO - Start bot...
2025-02-23 20:45:48,481 - root - INFO - start pulling...
2025-02-23 20:45:50,667 - root - ERROR - Error while deleting message: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: message to delete not found
2025-02-23 20:45:51,007 - root - ERROR - Error while deleting message: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: message to delete not found
2025-02-23 20:47:13,021 - root - INFO - Start bot...
2025-02-23 20:47:13,022 - root - INFO - start pulling...
2025-02-23 20:48:50,531 - root - INFO - end pulling...
2025-02-23 20:48:57,579 - root - INFO - Start bot...
2025-02-23 20:48:57,580 - root - INFO - start pulling...
2025-02-23 20:57:37,462 - root - INFO - Start bot...
2025-02-23 20:57:37,462 - root - INFO - start pulling...
2025-02-23 20:59:31,576 - root - INFO - Start bot...
2025-02-23 20:59:31,576 - root - INFO - start pulling...
2025-02-23 20:59:49,552 - root - INFO - Start bot...
2025-02-23 20:59:49,553 - root - INFO - start pulling...
2025-02-23 21:00:28,082 - root - INFO - Start bot...
2025-02-23 21:00:28,082 - root - INFO - start pulling...
2025-02-23 21:04:24,243 - root - INFO - Start bot...
2025-02-23 21:04:24,243 - root - INFO - start pulling...
2025-02-23 21:04:34,308 - root - INFO - end pulling...
2025-02-23 21:05:38,997 - root - INFO - Start bot...
2025-02-23 21:05:38,997 - root - INFO - start pulling...
2025-02-23 21:06:35,020 - root - INFO - end pulling...
2025-02-23 21:06:41,859 - root - INFO - Start bot...
2025-02-23 21:06:41,859 - root - INFO - start pulling...
2025-02-23 21:08:06,748 - root - INFO - Start bot...
2025-02-23 21:08:06,749 - root - INFO - start pulling...
2025-02-23 21:19:20,561 - root - INFO - Start bot...
2025-02-23 21:19:20,562 - root - INFO - start pulling...
2025-02-23 21:24:51,475 - root - INFO - Start bot...
2025-02-23 21:24:51,476 - root - INFO - start pulling...
2025-02-23 21:24:53,183 - root - ERROR - User already exist: 1062 (23000): Duplicate entry '7469530070' for key 'users.PRIMARY'
2025-02-23 21:24:53,185 - root - ERROR - User already exist: 1062 (23000): Duplicate entry '7469530070' for key 'users.PRIMARY'
2025-02-23 21:24:54,224 - root - ERROR - Error while deleting message: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: message can't be deleted for everyone
2025-02-23 21:32:32,758 - root - INFO - end pulling...
2025-02-23 21:35:17,940 - root - INFO - Start bot...
2025-02-23 21:35:17,941 - root - INFO - start pulling...
2025-02-23 21:36:41,932 - root - INFO - end pulling...
2025-02-23 21:36:45,357 - root - INFO - Start bot...
2025-02-23 21:36:45,357 - root - INFO - start pulling...
2025-02-23 21:42:19,201 - root - INFO - end pulling...
2025-02-23 21:42:21,444 - root - INFO - Start bot...
2025-02-23 21:42:21,444 - root - INFO - start pulling...
2025-02-23 21:43:28,014 - root - INFO - end pulling...
2025-02-23 21:44:38,355 - root - INFO - Start bot...
2025-02-23 21:44:38,355 - root - INFO - start pulling...
2025-02-23 21:44:42,354 - root - INFO - end pulling...
2025-02-23 21:48:14,100 - root - INFO - Start bot...
2025-02-23 21:48:14,100 - root - INFO - start pulling...
2025-02-23 21:49:12,794 - root - INFO - end pulling...
2025-02-23 21:52:12,857 - root - INFO - Start bot...
2025-02-23 21:52:12,858 - root - INFO - start pulling...
2025-02-23 21:56:04,673 - root - INFO - end pulling...
2025-02-23 21:56:06,977 - root - INFO - Start bot...
2025-02-23 21:56:06,977 - root - INFO - start pulling...
2025-02-23 21:58:32,227 - root - INFO - Start bot...
2025-02-23 21:58:32,228 - root - INFO - start pulling...
2025-02-23 22:00:04,681 - root - INFO - end pulling...
2025-02-23 22:00:09,568 - root - INFO - Start bot...
2025-02-23 22:00:09,569 - root - INFO - start pulling...
2025-02-23 22:00:47,463 - root - ERROR - User already exist: 1062 (23000): Duplicate entry '103416914' for key 'users.PRIMARY'
2025-02-23 22:03:31,942 - root - INFO - end pulling...
2025-02-23 22:03:34,944 - root - INFO - Start bot...
2025-02-23 22:03:34,945 - root - INFO - start pulling...
2025-02-23 22:05:01,160 - root - INFO - end pulling...
2025-02-23 22:05:03,202 - root - INFO - Start bot...
2025-02-23 22:05:03,202 - root - INFO - start pulling...
2025-02-23 22:06:09,571 - root - INFO - Start bot...
2025-02-23 22:06:09,571 - root - INFO - start pulling...
2025-02-23 22:06:13,977 - root - INFO - end pulling...
2025-02-23 22:06:20,449 - root - INFO - Start bot...
2025-02-23 22:06:20,449 - root - INFO - start pulling...
2025-02-23 22:06:43,271 - root - INFO - end pulling...
2025-02-23 22:21:50,815 - root - INFO - Start bot...
2025-02-23 22:21:50,852 - root - INFO - start pulling...
2025-02-23 22:28:47,003 - root - INFO - end pulling...
2025-02-23 22:28:49,392 - root - INFO - Start bot...
2025-02-23 22:28:49,392 - root - INFO - start pulling...
2025-02-23 22:30:45,466 - root - INFO - Start bot...
2025-02-23 22:30:45,467 - root - INFO - start pulling...
2025-02-23 22:32:29,010 - root - INFO - end pulling...
2025-02-23 22:32:31,223 - root - INFO - Start bot...
2025-02-23 22:33:06,673 - root - INFO - Start bot...
2025-02-23 22:33:06,673 - root - INFO - start pulling...
2025-02-23 22:33:28,379 - root - INFO - Start bot...
2025-02-23 22:33:28,380 - root - INFO - start pulling...
2025-02-23 22:36:13,242 - root - INFO - Start bot...
2025-02-23 22:36:13,242 - root - INFO - start pulling...
2025-02-23 22:40:32,258 - root - INFO - Start bot...
2025-02-23 22:40:32,259 - root - INFO - start pulling...
2025-02-23 22:42:13,915 - root - INFO - Start bot...
2025-02-23 22:42:13,915 - root - INFO - start pulling...
2025-02-23 22:43:53,025 - root - INFO - Start bot...
2025-02-23 22:43:53,025 - root - INFO - start pulling...
2025-02-23 22:45:29,171 - root - INFO - end pulling...
2025-02-23 22:45:33,343 - root - INFO - Start bot...
2025-02-23 22:45:33,343 - root - INFO - start pulling...
2025-02-23 22:47:00,876 - root - INFO - end pulling...
2025-02-23 22:47:03,931 - root - INFO - Start bot...
2025-02-23 22:47:03,931 - root - INFO - start pulling...
2025-02-23 22:47:50,599 - root - INFO - end pulling...
2025-02-23 22:47:54,732 - root - INFO - Start bot...
2025-02-23 22:47:54,732 - root - INFO - start pulling...
2025-02-23 22:49:00,007 - root - INFO - end pulling...
2025-02-23 22:49:02,373 - root - INFO - Start bot...
2025-02-23 22:49:02,373 - root - INFO - start pulling...
2025-02-23 22:53:17,669 - root - INFO - Start bot...
2025-02-23 22:53:17,669 - root - INFO - start pulling...
2025-02-23 22:54:47,403 - root - INFO - end pulling...
2025-02-23 22:54:49,568 - root - INFO - Start bot...
2025-02-23 22:54:49,568 - root - INFO - start pulling...
2025-02-23 22:56:49,306 - root - INFO - end pulling...
2025-02-23 22:56:51,172 - root - INFO - Start bot...
2025-02-23 22:56:51,173 - root - INFO - start pulling...
2025-02-23 22:57:01,835 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
2025-02-23 22:57:01,837 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\MochiServer_bot-2WiVER87\Lib\site-packages\telebot\__init__.py", line 1235, in __threaded_polling
    self.worker_pool.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Asus\.virtualenvs\MochiServer_bot-2WiVER87\Lib\site-packages\telebot\util.py", line 150, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Asus\.virtualenvs\MochiServer_bot-2WiVER87\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\.virtualenvs\MochiServer_bot-2WiVER87\Lib\site-packages\telebot\__init__.py", line 9233, in _run_middlewares_and_handler
    result = handler['function'](message)
  File "c:\Users\Asus\Desktop\PythonProjects\MochiServer_bot\main.py", line 386, in respond_config
    bot.send_message(chat_id=user_id, text=user_message.text)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\.virtualenvs\MochiServer_bot-2WiVER87\Lib\site-packages\telebot\__init__.py", line 1800, in send_message
    apihelper.send_message(
    ~~~~~~~~~~~~~~~~~~~~~~^
        self.token, chat_id, text,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        reply_parameters=reply_parameters, link_preview_options=link_preview_options, business_connection_id=business_connection_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        message_effect_id=message_effect_id, allow_paid_broadcast=allow_paid_broadcast))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\.virtualenvs\MochiServer_bot-2WiVER87\Lib\site-packages\telebot\apihelper.py", line 275, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "C:\Users\Asus\.virtualenvs\MochiServer_bot-2WiVER87\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Asus\.virtualenvs\MochiServer_bot-2WiVER87\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

2025-02-23 22:57:01,838 - root - INFO - end pulling...
2025-02-23 22:59:49,546 - root - INFO - Start bot...
2025-02-23 22:59:49,546 - root - INFO - start pulling...
2025-02-23 23:07:18,541 - root - INFO - end pulling...
2025-02-23 23:07:21,364 - root - INFO - Start bot...
2025-02-23 23:07:21,365 - root - INFO - start pulling...
2025-02-23 23:10:15,974 - root - INFO - end pulling...
2025-02-23 23:10:47,066 - root - INFO - Start bot...
2025-02-23 23:10:47,067 - root - INFO - start pulling...
2025-02-23 23:10:50,949 - root - ERROR - User already exist: 1062 (23000): Duplicate entry '103416914' for key 'users.PRIMARY'
2025-02-23 23:11:18,565 - root - ERROR - User already exist: 1062 (23000): Duplicate entry '7634084341' for key 'users.PRIMARY'
2025-02-23 23:15:09,481 - root - ERROR - User already exist: 1062 (23000): Duplicate entry '7634084341' for key 'users.PRIMARY'
2025-02-23 23:16:13,582 - root - INFO - end pulling...
2025-02-23 23:26:33,358 - root - INFO - Start bot...
2025-02-23 23:26:33,358 - root - INFO - start pulling...
2025-02-24 12:32:11,389 - root - INFO - Start bot...
2025-02-24 12:32:11,390 - root - INFO - start pulling...
2025-02-24 12:33:05,617 - root - INFO - Start bot...
2025-02-24 12:33:05,617 - root - INFO - start pulling...
2025-02-24 20:04:16,864 - root - INFO - Start bot...
2025-02-24 20:04:16,864 - root - INFO - start pulling...
2025-02-24 20:04:34,901 - root - ERROR - User already exist: 1062 (23000): Duplicate entry '103416914' for key 'users.PRIMARY'
2025-02-24 20:15:28,486 - root - INFO - end pulling...
2025-02-24 20:25:31,374 - root - INFO - Start bot...
2025-02-24 20:25:31,374 - root - INFO - start pulling...
2025-02-24 20:47:12,993 - root - INFO - end pulling...
2025-02-24 20:47:15,276 - root - INFO - Start bot...
2025-02-24 20:47:15,277 - root - INFO - start pulling...
2025-02-24 21:00:40,811 - root - INFO - end pulling...
2025-02-24 21:16:21,266 - root - INFO - Start bot...
2025-02-24 21:16:21,266 - root - INFO - start pulling...
2025-02-24 21:16:59,521 - root - ERROR - User already exist: 1062 (23000): Duplicate entry '103416914' for key 'users.PRIMARY'
2025-02-24 21:17:44,789 - root - INFO - User 103416914 balance updated
2025-02-24 21:22:45,385 - root - INFO - end pulling...
2025-02-24 21:25:02,457 - root - INFO - Start bot...
2025-02-24 21:25:02,457 - root - INFO - start pulling...
2025-02-24 21:26:25,574 - root - INFO - User 103416914 balance updated
2025-02-24 21:28:31,601 - root - INFO - end pulling...
2025-02-24 21:44:35,880 - root - INFO - Start bot...
2025-02-24 21:44:35,880 - root - INFO - start pulling...
2025-02-24 21:46:28,034 - root - ERROR - User already exist: 1062 (23000): Duplicate entry '7634084341' for key 'users.PRIMARY'
2025-02-24 21:47:57,868 - root - INFO - end pulling...
2025-02-24 21:50:39,448 - root - INFO - Start bot...
2025-02-24 21:50:39,449 - root - INFO - start pulling...
2025-02-24 21:50:42,089 - root - ERROR - User already exist: 1062 (23000): Duplicate entry '7634084341' for key 'users.PRIMARY'
2025-02-24 21:51:04,470 - root - INFO - Start bot...
2025-02-24 21:51:04,471 - root - INFO - start pulling...
2025-02-24 21:51:06,902 - root - ERROR - User already exist: 1062 (23000): Duplicate entry '7634084341' for key 'users.PRIMARY'
2025-02-24 21:55:30,361 - root - INFO - end pulling...
2025-02-24 21:55:34,752 - root - INFO - Start bot...
2025-02-24 21:55:34,753 - root - INFO - start pulling...
2025-02-24 22:01:03,731 - root - INFO - end pulling...
2025-02-24 22:02:59,263 - root - INFO - Start bot...
2025-02-24 22:02:59,263 - root - INFO - start pulling...
2025-02-24 22:03:05,756 - root - ERROR - User already exist: 1062 (23000): Duplicate entry '7634084341' for key 'users.PRIMARY'
2025-02-24 22:03:55,628 - root - ERROR - User already exist: 1062 (23000): Duplicate entry '7634084341' for key 'users.PRIMARY'
2025-02-24 22:07:20,646 - root - INFO - end pulling...
2025-02-24 22:26:25,383 - root - INFO - Start bot...
2025-02-24 22:26:25,383 - root - INFO - start pulling...
2025-02-24 22:26:27,011 - root - ERROR - User already exist: 1062 (23000): Duplicate entry '69724359' for key 'users.PRIMARY'
2025-02-24 22:26:27,012 - root - ERROR - User already exist: 1062 (23000): Duplicate entry '69724359' for key 'users.PRIMARY'
2025-02-24 22:28:17,124 - root - ERROR - User already exist: 1062 (23000): Duplicate entry '103416914' for key 'users.PRIMARY'
2025-02-24 22:39:22,718 - root - INFO - end pulling...
2025-02-24 22:39:25,395 - root - INFO - Start bot...
2025-02-24 22:39:25,395 - root - INFO - start pulling...
2025-02-24 22:43:43,163 - root - ERROR - User already exist: 1062 (23000): Duplicate entry '7469530070' for key 'users.PRIMARY'
2025-02-25 00:35:45,448 - root - INFO - Start bot...
2025-02-25 00:35:45,449 - root - INFO - start pulling...
2025-02-25 00:35:47,257 - root - ERROR - User already exist: 1062 (23000): Duplicate entry '7469530070' for key 'users.PRIMARY'
2025-02-25 00:36:40,244 - root - ERROR - Error while generating AI response: 

You tried to access openai.Completion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742

2025-02-25 00:36:46,060 - root - ERROR - Error while generating AI response: 

You tried to access openai.Completion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742

2025-02-25 00:43:24,088 - root - INFO - end pulling...
2025-02-25 00:43:34,145 - root - INFO - Start bot...
2025-02-25 00:43:34,145 - root - INFO - start pulling...
2025-02-25 00:43:53,910 - root - INFO - Start bot...
2025-02-25 00:43:53,910 - root - INFO - start pulling...
2025-02-25 00:44:06,570 - root - ERROR - Error while calling DeepSeek API: HTTPSConnectionPool(host='api.deepseek.ai', port=443): Max retries exceeded with url: /v1/respond (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000018D00782710>: Failed to resolve 'api.deepseek.ai' ([Errno 11001] getaddrinfo failed)"))
2025-02-25 00:44:06,571 - root - ERROR - Error while calling DeepSeek API: HTTPSConnectionPool(host='api.deepseek.ai', port=443): Max retries exceeded with url: /v1/respond (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000018D00782850>: Failed to resolve 'api.deepseek.ai' ([Errno 11001] getaddrinfo failed)"))
2025-02-25 00:44:46,368 - root - INFO - end pulling...
2025-02-25 00:56:25,762 - root - INFO - Start bot...
2025-02-25 00:56:25,762 - root - INFO - start pulling...
2025-02-25 00:56:38,680 - httpx - INFO - HTTP Request: GET https://llmhacker-deepseek-r1-distill-llama-8b.hf.space/config "HTTP/1.1 200 OK"
2025-02-25 00:56:39,732 - httpx - INFO - HTTP Request: GET https://llmhacker-deepseek-r1-distill-llama-8b.hf.space/info?serialize=False "HTTP/1.1 200 OK"
2025-02-25 00:56:40,872 - httpx - INFO - HTTP Request: GET https://llmhacker-deepseek-r1-distill-llama-8b.hf.space/heartbeat/6a40a9f7-a80f-4b85-ab95-416b258b27c9 "HTTP/1.1 200 OK"
2025-02-25 00:56:41,652 - httpx - INFO - HTTP Request: POST https://llmhacker-deepseek-r1-distill-llama-8b.hf.space/queue/join "HTTP/1.1 200 OK"
2025-02-25 00:56:42,979 - httpx - INFO - HTTP Request: GET https://llmhacker-deepseek-r1-distill-llama-8b.hf.space/queue/data?session_hash=6a40a9f7-a80f-4b85-ab95-416b258b27c9 "HTTP/1.1 200 OK"
2025-02-25 00:57:13,423 - root - INFO - Start bot...
2025-02-25 00:57:13,423 - root - INFO - start pulling...
2025-02-25 00:57:20,936 - httpx - INFO - HTTP Request: GET https://llmhacker-deepseek-r1-distill-llama-8b.hf.space/config "HTTP/1.1 200 OK"
2025-02-25 00:57:22,594 - httpx - INFO - HTTP Request: GET https://llmhacker-deepseek-r1-distill-llama-8b.hf.space/info?serialize=False "HTTP/1.1 200 OK"
2025-02-25 00:57:24,997 - httpx - INFO - HTTP Request: POST https://llmhacker-deepseek-r1-distill-llama-8b.hf.space/queue/join "HTTP/1.1 200 OK"
2025-02-25 00:57:25,284 - httpx - INFO - HTTP Request: GET https://llmhacker-deepseek-r1-distill-llama-8b.hf.space/heartbeat/0b1f6a2d-670a-4c5b-8cc3-a9090f5750c5 "HTTP/1.1 200 OK"
2025-02-25 00:57:26,420 - httpx - INFO - HTTP Request: GET https://llmhacker-deepseek-r1-distill-llama-8b.hf.space/queue/data?session_hash=0b1f6a2d-670a-4c5b-8cc3-a9090f5750c5 "HTTP/1.1 200 OK"
2025-02-25 00:58:07,730 - root - INFO - end pulling...
2025-02-25 00:58:44,415 - root - INFO - Start bot...
2025-02-25 00:58:44,415 - root - INFO - start pulling...
2025-02-25 00:58:51,508 - httpx - INFO - HTTP Request: GET https://llmhacker-deepseek-r1-distill-llama-8b.hf.space/config "HTTP/1.1 200 OK"
2025-02-25 00:58:52,487 - httpx - INFO - HTTP Request: GET https://llmhacker-deepseek-r1-distill-llama-8b.hf.space/info?serialize=False "HTTP/1.1 200 OK"
2025-02-25 00:58:53,702 - httpx - INFO - HTTP Request: POST https://llmhacker-deepseek-r1-distill-llama-8b.hf.space/queue/join "HTTP/1.1 200 OK"
2025-02-25 00:58:53,848 - httpx - INFO - HTTP Request: GET https://llmhacker-deepseek-r1-distill-llama-8b.hf.space/heartbeat/726dda12-1690-419e-bd03-1751f16d2092 "HTTP/1.1 200 OK"
2025-02-25 00:58:54,925 - httpx - INFO - HTTP Request: GET https://llmhacker-deepseek-r1-distill-llama-8b.hf.space/queue/data?session_hash=726dda12-1690-419e-bd03-1751f16d2092 "HTTP/1.1 200 OK"
2025-02-25 01:01:01,851 - root - INFO - end pulling...
2025-02-25 01:01:05,618 - root - INFO - Start bot...
2025-02-25 01:01:05,619 - root - INFO - start pulling...
2025-02-25 04:50:27,630 - root - ERROR - User already exist: 1062 (23000): Duplicate entry '7469530070' for key 'users.PRIMARY'
2025-02-25 12:50:47,075 - root - INFO - Start bot...
2025-02-25 12:50:47,076 - root - INFO - start pulling...
2025-02-25 12:51:25,443 - httpx - INFO - HTTP Request: GET https://llmhacker-deepseek-r1-distill-llama-8b.hf.space/config "HTTP/1.1 200 OK"
2025-02-25 12:51:26,484 - httpx - INFO - HTTP Request: GET https://llmhacker-deepseek-r1-distill-llama-8b.hf.space/info?serialize=False "HTTP/1.1 200 OK"
2025-02-25 12:52:22,371 - root - INFO - Start bot...
2025-02-25 12:52:22,371 - root - INFO - start pulling...
2025-02-25 12:52:33,047 - httpx - INFO - HTTP Request: GET https://llmhacker-deepseek-r1-distill-llama-8b.hf.space/config "HTTP/1.1 200 OK"
2025-02-25 12:52:34,538 - httpx - INFO - HTTP Request: GET https://llmhacker-deepseek-r1-distill-llama-8b.hf.space/info?serialize=False "HTTP/1.1 200 OK"
2025-02-25 12:52:35,980 - httpx - INFO - HTTP Request: POST https://llmhacker-deepseek-r1-distill-llama-8b.hf.space/queue/join "HTTP/1.1 200 OK"
2025-02-25 12:52:36,813 - httpx - INFO - HTTP Request: GET https://llmhacker-deepseek-r1-distill-llama-8b.hf.space/heartbeat/9fe954af-a60e-4f5b-874e-2337fd97b933 "HTTP/1.1 200 OK"
2025-02-25 12:52:37,237 - httpx - INFO - HTTP Request: GET https://llmhacker-deepseek-r1-distill-llama-8b.hf.space/queue/data?session_hash=9fe954af-a60e-4f5b-874e-2337fd97b933 "HTTP/1.1 200 OK"
2025-02-25 12:53:47,589 - httpx - INFO - HTTP Request: GET https://llmhacker-deepseek-r1-distill-llama-8b.hf.space/config "HTTP/1.1 200 OK"
2025-02-25 12:53:48,863 - httpx - INFO - HTTP Request: GET https://llmhacker-deepseek-r1-distill-llama-8b.hf.space/info?serialize=False "HTTP/1.1 200 OK"
2025-02-25 12:53:50,063 - httpx - INFO - HTTP Request: GET https://llmhacker-deepseek-r1-distill-llama-8b.hf.space/heartbeat/7254e09b-52f1-4489-9c32-61941109d642 "HTTP/1.1 200 OK"
2025-02-25 12:53:50,083 - httpx - INFO - HTTP Request: POST https://llmhacker-deepseek-r1-distill-llama-8b.hf.space/queue/join "HTTP/1.1 200 OK"
2025-02-25 12:53:51,055 - httpx - INFO - HTTP Request: GET https://llmhacker-deepseek-r1-distill-llama-8b.hf.space/queue/data?session_hash=7254e09b-52f1-4489-9c32-61941109d642 "HTTP/1.1 200 OK"
2025-02-25 12:56:28,940 - root - INFO - Start bot...
2025-02-25 12:56:28,940 - root - INFO - start pulling...
2025-02-25 13:00:17,903 - root - INFO - end pulling...
2025-02-25 13:00:24,790 - root - INFO - Start bot...
2025-02-25 13:00:24,791 - root - INFO - start pulling...
2025-02-25 13:00:44,542 - httpx - INFO - HTTP Request: GET https://llmhacker-deepseek-r1-distill-llama-8b.hf.space/config "HTTP/1.1 200 OK"
2025-02-25 13:00:45,765 - httpx - INFO - HTTP Request: GET https://llmhacker-deepseek-r1-distill-llama-8b.hf.space/info?serialize=False "HTTP/1.1 200 OK"
2025-02-25 13:00:46,923 - httpx - INFO - HTTP Request: GET https://llmhacker-deepseek-r1-distill-llama-8b.hf.space/heartbeat/e173654a-3e9d-4d28-a0b9-f16e6d8e9c5a "HTTP/1.1 200 OK"
2025-02-25 13:00:46,938 - httpx - INFO - HTTP Request: POST https://llmhacker-deepseek-r1-distill-llama-8b.hf.space/queue/join "HTTP/1.1 200 OK"
2025-02-25 13:00:48,002 - httpx - INFO - HTTP Request: GET https://llmhacker-deepseek-r1-distill-llama-8b.hf.space/queue/data?session_hash=e173654a-3e9d-4d28-a0b9-f16e6d8e9c5a "HTTP/1.1 200 OK"
2025-02-25 13:13:02,872 - root - INFO - end pulling...
2025-02-25 13:13:32,326 - root - INFO - Start bot...
2025-02-25 13:13:32,326 - root - INFO - start pulling...
2025-02-25 13:15:20,530 - root - INFO - Start bot...
2025-02-25 13:15:20,530 - root - INFO - start pulling...
2025-02-25 13:15:28,063 - root - ERROR - Error while calling DeepSeek API: Expecting value: line 1 column 1 (char 0)
2025-02-25 13:15:36,450 - root - ERROR - Error while calling DeepSeek API: Expecting value: line 1 column 1 (char 0)
2025-02-25 13:18:00,057 - root - INFO - end pulling...
2025-02-25 13:18:07,610 - root - INFO - Start bot...
2025-02-25 13:18:07,611 - root - INFO - start pulling...
2025-02-25 14:56:40,131 - root - ERROR - Error while calling DeepSeek API: Expecting value: line 1 column 1 (char 0)
2025-02-25 14:56:50,161 - root - ERROR - Error while calling DeepSeek API: Expecting value: line 1 column 1 (char 0)
2025-02-25 14:57:07,113 - root - ERROR - Error while calling DeepSeek API: Expecting value: line 1 column 1 (char 0)
2025-02-25 15:07:54,043 - root - ERROR - User already exist: 1062 (23000): Duplicate entry '103416914' for key 'users.PRIMARY'
2025-03-01 17:12:35,116 - root - INFO - Start bot...
2025-03-01 17:12:35,117 - root - INFO - start pulling...
2025-03-01 17:13:15,246 - root - ERROR - User already exist: 1062 (23000): Duplicate entry '103416914' for key 'users.PRIMARY'
2025-03-01 17:53:43,327 - root - INFO - end pulling...
2025-03-01 17:53:45,979 - root - INFO - Start bot...
2025-03-01 17:53:45,979 - root - INFO - start pulling...
2025-03-01 17:56:49,869 - root - INFO - end pulling...
2025-03-01 17:58:10,217 - root - INFO - Start bot...
2025-03-01 17:58:10,218 - root - INFO - start pulling...
2025-03-01 18:07:29,085 - root - INFO - end pulling...
2025-03-01 18:07:32,387 - root - INFO - Start bot...
2025-03-01 18:07:32,387 - root - INFO - start pulling...
2025-03-01 18:07:49,847 - root - ERROR - User already exist: 1062 (23000): Duplicate entry '7634084341' for key 'users.PRIMARY'
2025-03-01 18:10:06,074 - root - INFO - end pulling...
2025-03-01 18:11:38,503 - root - INFO - Start bot...
2025-03-01 18:11:38,504 - root - INFO - start pulling...
2025-03-01 18:17:56,425 - root - INFO - end pulling...
2025-03-02 17:50:35,027 - root - INFO - Start bot...
2025-03-02 17:50:35,027 - root - INFO - start pulling...
2025-03-02 17:51:30,232 - root - INFO - end pulling...
2025-03-02 17:52:37,313 - root - INFO - Start bot...
2025-03-02 17:52:37,313 - root - INFO - start pulling...
2025-03-02 17:53:12,584 - root - INFO - end pulling...
2025-03-02 17:53:32,677 - root - INFO - Start bot...
2025-03-02 17:53:32,677 - root - INFO - start pulling...
2025-03-02 17:54:36,890 - root - INFO - end pulling...
2025-03-02 17:56:33,419 - root - INFO - Start bot...
2025-03-02 17:56:33,419 - root - INFO - start pulling...
2025-03-02 17:57:19,437 - root - INFO - end pulling...
2025-03-02 17:58:48,776 - root - INFO - Start bot...
2025-03-02 17:58:48,777 - root - INFO - start pulling...
2025-03-02 17:59:22,909 - root - INFO - end pulling...
2025-03-04 16:48:21,531 - root - INFO - Start bot...
2025-03-04 16:48:21,532 - root - INFO - start pulling...
2025-03-04 16:53:18,592 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-03-04 16:53:18,594 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\MochiServer_bot-2WiVER87\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Asus\.virtualenvs\MochiServer_bot-2WiVER87\Lib\site-packages\telebot\util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Asus\.virtualenvs\MochiServer_bot-2WiVER87\Lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\.virtualenvs\MochiServer_bot-2WiVER87\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\Asus\.virtualenvs\MochiServer_bot-2WiVER87\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\Asus\.virtualenvs\MochiServer_bot-2WiVER87\Lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Asus\.virtualenvs\MochiServer_bot-2WiVER87\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Asus\.virtualenvs\MochiServer_bot-2WiVER87\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-03-04 16:53:18,594 - root - INFO - end pulling...
2025-03-10 00:44:54,037 - root - INFO - Start bot...
2025-03-10 00:44:54,037 - root - INFO - start pulling...
2025-03-10 00:46:19,110 - root - ERROR - User already exist: 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0
2025-03-10 00:46:25,750 - root - ERROR - User already exist: 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0
2025-03-10 01:36:18,590 - root - INFO - Start bot...
2025-03-10 01:36:18,590 - root - INFO - start pulling...
2025-03-10 01:37:58,761 - root - ERROR - Error while checking or updating test config usage: 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0
2025-03-10 01:47:05,853 - root - INFO - Start bot...
2025-03-10 01:47:05,853 - root - INFO - start pulling...
2025-03-10 01:48:28,333 - root - INFO - Start bot...
2025-03-10 01:48:28,334 - root - INFO - start pulling...
2025-03-10 01:48:31,689 - root - ERROR - User already exist: 1062 (23000): Duplicate entry '103416914' for key 'users.PRIMARY'
2025-03-10 01:55:19,719 - root - ERROR - User already exist: 1062 (23000): Duplicate entry '103416914' for key 'users.PRIMARY'
2025-03-10 02:08:07,713 - root - INFO - Start bot...
2025-03-10 02:08:07,713 - root - INFO - start pulling...
2025-03-10 02:10:14,766 - root - INFO - Start bot...
2025-03-10 02:10:14,766 - root - INFO - start pulling...
2025-03-10 02:10:15,763 - root - ERROR - User already exist: 1062 (23000): Duplicate entry '103416914' for key 'users.PRIMARY'
2025-03-10 02:11:50,414 - root - INFO - Start bot...
2025-03-10 02:11:50,415 - root - INFO - start pulling...
2025-03-10 02:11:53,917 - root - ERROR - User already exist: 1062 (23000): Duplicate entry '103416914' for key 'users.PRIMARY'
2025-03-10 02:12:31,236 - root - INFO - User 103416914 added to database
